apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: be-pipeline-qa
spec:
  resources:
    - name: app-be-git-repo
      type: git
    - name: app-be-image-qa
      type: image

  params:
    - name: IMAGE_NAME
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - name: DC_NAME
      type: string

  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.GIT_REVISION)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace

    - name: bake
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace

    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - $(params.DC_NAME)
            - '-n app-be-dev'
      runAfter:
        - bake
      taskRef:
        kind: ClusterTask
        name: openshift-client

  workspaces:
    - name: workspace
