kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitdir
  namespace: app-fe-qa
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
