kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-fe
  namespace: app-fe-qa
  labels:
    app: app-fe
spec:
  host: app-fe-qa.apps.cluster-{{ guid }}.{{ ocp4_base_domain }}
  to:
    kind: Service
    name: app-fe
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
