apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fe-qa-build-and-deploy
  namespace: app-fe-qa
spec:
  params:
    - default: 'image-registry.openshift-image-registry.svc:5000/app-fe-qa/app-fe:qa'
      name: IMAGE_NAME
      type: string
    - default: 'https://github.com/redhat-sap/sap-side-by-side-fe.git'
      name: GIT_REPO
      type: string
    - default: qa
      name: GIT_REVISION
      type: string
    - default: app-fe
      name: DC_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - latest
            - $(params.DC_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
