apiVersion: v1
kind: Namespace
metadata:
  name: app-fe-cicd
  annotations:
    openshift.io/description: "Agile integration with SAP - Frontend Microservice - CI/CD"
    openshift.io/display-name: "Agile integration with SAP - Frontend Microservice - CI/CD"
spec: {}