apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-build
spec:
  params:
    - name: npm_args
      type: string
      default: run-script build
  steps:
    - image: registry.access.redhat.com/ubi8/nodejs-12
      name: build
      resources: {}
      script: |
        #!/bin/sh
        set -eu -o pipefail
        npm install
        npm $(inputs.params.NPM_ARGS)
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source