apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: fe-build-and-deploy-triggertemplate
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: dev
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fe-build-and-deploy-
      spec:
        pipelineRef:
          name: fe-build-and-deploy
        params:
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/app-fe-dev/app-fe:dev'
          - name: GIT_REPO
            value: 'https://github.com/redhat-sap/sap-side-by-side-fe.git'
          - name: GIT_REVISION
            value: dev
          - name: DC_NAME
            value: app-fe
        resources:
          - name: app-fe-git-repo
            resourceRef:
              name: app-fe-git-repo
          - name: app-fe-image-dev
            resourceRef:
              name: app-fe-image-dev
          - name: app-fe-image-qa
            resourceRef:
              name: app-fe-image-qa
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: gitdir
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: github-triggerbinding
      template:
        name: fe-build-and-deploy-triggertemplate
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
  name: el-webhook
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: el-webhook
    weight: 100
