apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: app-fe-pipeline-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
      - kind: TriggerBinding
        ref: app-fe-pipeline-binding
      template:
        name: app-fe-pipeline-template

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: app-fe-pipeline-binding
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-fe-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: app-fe-pipeline-run-$(tt.params.gitrevision)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: fe-build-and-deploy
        resources:
          - name: app-fe-git-repo
            resourceRef:
              name: app-fe-git-repo
          - name: app-fe-image-dev
            resourceRef:
              name: app-fe-image-dev
          - name: app-fe-image-qa
            resourceRef:
              name: app-fe-image-qa
        params:
          - name: IMAGE_NAME
            value: 'image-registry.openshift-image-registry.svc:5000/app-fe-$(params.gitrevision)/app-fe:$(params.gitrevision)'
          - name: GIT_REPO
            value: 'https://github.com/redhat-sap/sap-side-by-side-fe.git'
          - name: GIT_REVISION
            value: $(params.gitrevision)
          - name: DC_NAME
            value: app-fe
        workspaces:
          - name: workspace
            persistentVolumeClaim:
              claimName: gitdir

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-fe-pipeline-webhook
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: el-app-fe-pipeline-listener
    weight: 100
