kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: app-be
  namespace: app-be-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'app-be:dev'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/redhat-sap/sap-side-by-side-be.git'
      ref: master
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: app-be-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: app-be-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
