kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-admin-be-dev
  namespace: app-be-dev
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: app-be-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin