kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-be
  namespace: app-be-dev
  labels:
    app: app-be
spec:
  host: app-be.apps.cluster-4515.4515.example.opentlc.com
  to:
    kind: Service
    name: app-be
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None